# Site settings
title: Scratch Blog
email: scratch@ausiv.com
description: > # this means to ignore newlines until "baseurl:"
   Follow the adventure of a dad and his kids as they discover where their food comes from.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scratch.ausiv.com" # the base hostname & protocol for your site
twitter_username: ausiv
github_username:  ausiv
paginate: 10

# Build settings
markdown: kramdown
